/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Sellan
 */
public class VtnAerolinea extends javax.swing.JFrame {

    /**
     * Creates new form VtnAerolinea
     */
    public VtnAerolinea() {
        initComponents();
       
 
        setResizable(false);
        this.setLocationRelativeTo(this);
        EscalarImageLabel(jlabelImagenAvion, "src/assets/imagenAvion.jpeg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblAsiento1 = new javax.swing.JLabel();
        jLblAsiento2 = new javax.swing.JLabel();
        jLblAsiento3 = new javax.swing.JLabel();
        jLblAsiento4 = new javax.swing.JLabel();
        jLblAsiento5 = new javax.swing.JLabel();
        jLblAsiento6 = new javax.swing.JLabel();
        jLblAsiento7 = new javax.swing.JLabel();
        jLblAsiento8 = new javax.swing.JLabel();
        jLblAsiento9 = new javax.swing.JLabel();
        jLblAsiento10 = new javax.swing.JLabel();
        jLblAsiento11 = new javax.swing.JLabel();
        jLblAsiento12 = new javax.swing.JLabel();
        jLblAsiento13 = new javax.swing.JLabel();
        jLblAsiento14 = new javax.swing.JLabel();
        jLblAsiento15 = new javax.swing.JLabel();
        jLblAsiento16 = new javax.swing.JLabel();
        jLblAsiento17 = new javax.swing.JLabel();
        jLblAsiento18 = new javax.swing.JLabel();
        jLblAsiento19 = new javax.swing.JLabel();
        jLblAsiento20 = new javax.swing.JLabel();
        jLblAsiento21 = new javax.swing.JLabel();
        jLblAsiento22 = new javax.swing.JLabel();
        jLblAsiento23 = new javax.swing.JLabel();
        jLblAsiento24 = new javax.swing.JLabel();
        jLblAsiento25 = new javax.swing.JLabel();
        jLblAsiento26 = new javax.swing.JLabel();
        jLblAsientol27 = new javax.swing.JLabel();
        jLblAsiento28 = new javax.swing.JLabel();
        jLblAsiento29 = new javax.swing.JLabel();
        jLblAsiento30 = new javax.swing.JLabel();
        jlabelImagenAvion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservar Asiento");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1140, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblAsiento1.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento1.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento1.setText("jLabel1");
        jLblAsiento1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento1.setOpaque(true);
        getContentPane().add(jLblAsiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 30, 30));

        jLblAsiento2.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento2.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento2.setText("jLabel1");
        jLblAsiento2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento2.setOpaque(true);
        getContentPane().add(jLblAsiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 30, 30));

        jLblAsiento3.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento3.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento3.setText("jLabel1");
        jLblAsiento3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento3.setOpaque(true);
        getContentPane().add(jLblAsiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 30, 30));

        jLblAsiento4.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento4.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento4.setText("jLabel1");
        jLblAsiento4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento4.setOpaque(true);
        getContentPane().add(jLblAsiento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 30, 30));

        jLblAsiento5.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento5.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento5.setText("jLabel1");
        jLblAsiento5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento5.setOpaque(true);
        getContentPane().add(jLblAsiento5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 30, 30));

        jLblAsiento6.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento6.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento6.setText("jLabel1");
        jLblAsiento6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento6.setOpaque(true);
        getContentPane().add(jLblAsiento6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 30, 30));

        jLblAsiento7.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento7.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento7.setText("jLabel1");
        jLblAsiento7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento7.setOpaque(true);
        getContentPane().add(jLblAsiento7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 30, 30));

        jLblAsiento8.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento8.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento8.setText("jLabel1");
        jLblAsiento8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento8.setOpaque(true);
        getContentPane().add(jLblAsiento8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 30, 30));

        jLblAsiento9.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento9.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento9.setText("jLabel1");
        jLblAsiento9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento9.setOpaque(true);
        getContentPane().add(jLblAsiento9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 30, 30));

        jLblAsiento10.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento10.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento10.setText("jLabel1");
        jLblAsiento10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento10.setOpaque(true);
        getContentPane().add(jLblAsiento10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 30, 30));

        jLblAsiento11.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento11.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento11.setText("jLabel1");
        jLblAsiento11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento11.setOpaque(true);
        getContentPane().add(jLblAsiento11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 30, 30));

        jLblAsiento12.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento12.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento12.setText("jLabel1");
        jLblAsiento12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento12.setOpaque(true);
        getContentPane().add(jLblAsiento12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 30, 30));

        jLblAsiento13.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento13.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento13.setText("jLabel1");
        jLblAsiento13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento13.setOpaque(true);
        getContentPane().add(jLblAsiento13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 30, 30));

        jLblAsiento14.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento14.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento14.setText("jLabel1");
        jLblAsiento14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento14.setOpaque(true);
        getContentPane().add(jLblAsiento14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 30, 30));

        jLblAsiento15.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento15.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento15.setText("jLabel1");
        jLblAsiento15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento15.setOpaque(true);
        getContentPane().add(jLblAsiento15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 30, 30));

        jLblAsiento16.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento16.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento16.setText("jLabel1");
        jLblAsiento16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento16.setOpaque(true);
        getContentPane().add(jLblAsiento16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 30, 30));

        jLblAsiento17.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento17.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento17.setText("jLabel1");
        jLblAsiento17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento17.setOpaque(true);
        getContentPane().add(jLblAsiento17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 30, 30));

        jLblAsiento18.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento18.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento18.setText("jLabel1");
        jLblAsiento18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento18.setOpaque(true);
        getContentPane().add(jLblAsiento18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 30, 30));

        jLblAsiento19.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento19.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento19.setText("jLabel1");
        jLblAsiento19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento19.setOpaque(true);
        getContentPane().add(jLblAsiento19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 30, 30));

        jLblAsiento20.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento20.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento20.setText("jLabel1");
        jLblAsiento20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento20.setOpaque(true);
        getContentPane().add(jLblAsiento20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 30, 30));

        jLblAsiento21.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento21.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento21.setText("jLabel1");
        jLblAsiento21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento21.setOpaque(true);
        getContentPane().add(jLblAsiento21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 30, 30));

        jLblAsiento22.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento22.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento22.setText("jLabel1");
        jLblAsiento22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento22.setOpaque(true);
        getContentPane().add(jLblAsiento22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 30, 30));

        jLblAsiento23.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento23.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento23.setText("jLabel1");
        jLblAsiento23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento23.setOpaque(true);
        getContentPane().add(jLblAsiento23, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 30, 30));

        jLblAsiento24.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento24.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento24.setText("jLabel1");
        jLblAsiento24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento24.setOpaque(true);
        getContentPane().add(jLblAsiento24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 30, 30));

        jLblAsiento25.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento25.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento25.setText("jLabel1");
        jLblAsiento25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento25.setOpaque(true);
        getContentPane().add(jLblAsiento25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 30, 30));

        jLblAsiento26.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento26.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento26.setText("jLabel1");
        jLblAsiento26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento26.setOpaque(true);
        getContentPane().add(jLblAsiento26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 30, 30));

        jLblAsientol27.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsientol27.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsientol27.setText("jLabel1");
        jLblAsientol27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsientol27.setOpaque(true);
        getContentPane().add(jLblAsientol27, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 30, 30));

        jLblAsiento28.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento28.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento28.setText("jLabel1");
        jLblAsiento28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento28.setOpaque(true);
        getContentPane().add(jLblAsiento28, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 30, 30));

        jLblAsiento29.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento29.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento29.setText("jLabel1");
        jLblAsiento29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento29.setOpaque(true);
        getContentPane().add(jLblAsiento29, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 30, 30));

        jLblAsiento30.setBackground(new java.awt.Color(102, 255, 102));
        jLblAsiento30.setForeground(new java.awt.Color(102, 255, 102));
        jLblAsiento30.setText("jLabel1");
        jLblAsiento30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblAsiento30.setOpaque(true);
        getContentPane().add(jLblAsiento30, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 30, 30));
        getContentPane().add(jlabelImagenAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 210));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1140, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 102, 102), null), "Ventanilla 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 220, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAerolinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAerolinea().setVisible(true);
            }
        });
    }
    
    private void EscalarImageLabel(JLabel labelImagen, String ruta){
        ImageIcon image = new ImageIcon(ruta);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelImagen.getWidth(), labelImagen.getHeight(), Image.SCALE_DEFAULT));
        labelImagen.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblAsiento1;
    private javax.swing.JLabel jLblAsiento10;
    private javax.swing.JLabel jLblAsiento11;
    private javax.swing.JLabel jLblAsiento12;
    private javax.swing.JLabel jLblAsiento13;
    private javax.swing.JLabel jLblAsiento14;
    private javax.swing.JLabel jLblAsiento15;
    private javax.swing.JLabel jLblAsiento16;
    private javax.swing.JLabel jLblAsiento17;
    private javax.swing.JLabel jLblAsiento18;
    private javax.swing.JLabel jLblAsiento19;
    private javax.swing.JLabel jLblAsiento2;
    private javax.swing.JLabel jLblAsiento20;
    private javax.swing.JLabel jLblAsiento21;
    private javax.swing.JLabel jLblAsiento22;
    private javax.swing.JLabel jLblAsiento23;
    private javax.swing.JLabel jLblAsiento24;
    private javax.swing.JLabel jLblAsiento25;
    private javax.swing.JLabel jLblAsiento26;
    private javax.swing.JLabel jLblAsiento28;
    private javax.swing.JLabel jLblAsiento29;
    private javax.swing.JLabel jLblAsiento3;
    private javax.swing.JLabel jLblAsiento30;
    private javax.swing.JLabel jLblAsiento4;
    private javax.swing.JLabel jLblAsiento5;
    private javax.swing.JLabel jLblAsiento6;
    private javax.swing.JLabel jLblAsiento7;
    private javax.swing.JLabel jLblAsiento8;
    private javax.swing.JLabel jLblAsiento9;
    private javax.swing.JLabel jLblAsientol27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlabelImagenAvion;
    // End of variables declaration//GEN-END:variables
}
